resources:
  - name: src_repo_rbv2_distribution_dynamic_matrix
    type: GitRepo
    configuration:
      path: harshkumar1/RBv2-Distribution-DynamicMatrix
      gitProvider: hk_github
      branches:
        include: ^main$
      cloneProtocol: https
      buildOn:
        commit: true
# TODO: Listen for artifct to a repo and automatically create a RB
pipelines:
  - name: demo_create_rb_pipeline
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: create_rbv2
        type: Bash
        configuration:
          inputResources:
            - name: src_repo_rbv2_distribution_dynamic_matrix
          integrations:
            - name: hk_artifactory
            - name: jpdPlatform
            - name: hk_rb_signing_key
        execution:
          onExecute:
            - task: jfrog/release-bundle@v1.0.0
              id: create-release-bundle
              input:
                jfrogPlatformToken: jpdPlatform
                name: release_bundle_cpp
                version: 1.0.1
                sourceArtifactPaths:
                  - "path": "generic-repo-local/compressor"
                signing: hk_rb_signing_key
          onFailure:
            - echo "Task Test failed"
          onSuccess:
            - echo "Test Task execution is a success without any errors"
          onComplete:
            - echo "Test Task execution completed.