pipelines:
  - name: dynamic_matrix_step
    configuration:
      environmentVariables:
        readOnly:
          multivalue_env_variable:
            defaultMultipleValues: ["server_1"]
            description: "testing"
            values: ["server_1", "server_2", "server_3", "server_4"]
            allowCustom: true
            allowMultipleValues: true
    steps:
      - name: dynamic_matrix_env_ui
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - multiValue_env: ${multivalue_env_variable} #picking up value from environment variable
        execution:
          onExecute:
            - echo ${multiValue_env}
    
      - name: setting_env_variable
        type: Bash
        configuration:
          inputResources:
            - name: src_repo_rbv2_distribution_dynamic_matrix
        execution:
          onExecute:
            - add_run_variables servers_array="server-z,server-y,server-x"

      - name: dynamic_matrix_env_step
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: setting_env_variable
        stepletMultipliers:
          environmentVariables:
            - multiValue_env: ${servers_array} #picking up value from environment variable
        execution:
          onExecute:
            - echo ${servers_array}