pipelines:
  - name: dynamic_matrix_step
    configuration:
      environmentVariables:
        readOnly:
          multivalue_env_variable:
            defaultMultipleValues: ["server_1"]
            description: "testing"
            values: ["server_1", "server_2", "server_3", "server_4"]
            allowCustom: true
            allowMultipleValues: true
    steps:
    
      - name: dynamic_matrix
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - multiValue_env: ${multivalue_env_variable} #picking up value from environment variable
        execution:
          onExecute:
            - echo ${multiValue_env}