resources:
  - name: src_repo_rbv2_distribution_dynamic matrix
    type: GitRepo
    configuration:
      path: harshkumar1/RBv2-Distribution-DynamicMatrix
      gitProvider: hk_github
      branches:
        include: ^main$
      cloneProtocol: https
      buildOn:
        commit: true

pipelines:
  - name: release_management
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: create_rbv2
        type: Bash
        configuration:
          inputResources:
            - name: src_repo_rbv2_distribution_dynamic matrix
          integrations:
            - name: hk_artifactory
            - name: jpdPlatform
        execution:
          onExecute:
            - task: jfrog/release-bundle@v0.0.1
              id: create-release-bundle
              input:
                jfrogPlatformToken: jpdPlatform
                name: release_bundle_cpp
                version: 1.0.1
                sourceArtifactPaths:
                  - "path": "demo-docker-local/demo_microservice_1/10/manifest.json"
          onFailure:
            - echo "Task Test failed"
          onSuccess:
            - echo "Test Task execution is a success without any errors"
          onComplete:
            - echo "Test Task execution completed.